### ISSUE TITLE
Modèle v0.4

### ISSUE THREAD

**Issue by lissyx** [Common-Voice/commonvoice-fr#88]
Bloqueurs :
 - [x] Mettre à jour le fork DeepSpeech sur `master` / `v0.7.0` #89 
 - [x] Intégrer Common Voice Français v3 (release `fr_412h_2019-12-10`) #90
 - [x] Améliorer le filtrage de Common Voice v3 #99
 - [x] Optimisation du modèle de langue en limitant aux mots les plus fréquents #96 
 - [ ] ~~Génération du LM #83~~
 - [x] Partager le `best_dev` #94 
 - [x] Exports depuis `best_dev` #95 (prêt mais attends un patch sur DeepSpeech)
 - [x] Comparaison Common Voice v3 FR -- Duplicatas #102

Non bloqueurs :
 - [ ] Augmenter le corpus de son avec de nouveaux jeux de données #91
 - [ ] Expérimenter avec les augmentations (pitch, noise) #92

**Comment by lissyx** [comment]
Plus ou moins tout est bouclé, j'essaie de comprendre pourquoi comme expliqué dans #102 le code exporte un peu trop tôt, parce que du coup c'est difficile de bien avoir quelque chose de reproductible.

**Comment by lissyx** [comment]
> Plus ou moins tout est bouclé, j'essaie de comprendre pourquoi comme expliqué dans #102 le code exporte un peu trop tôt, parce que du coup c'est difficile de bien avoir quelque chose de reproductible.

Ça semble être un effet de bord de l'utilisation de `automatic_mixed_precision`. Quand on est à faire une release, ça semble bien de le désactiver.

**Comment by lissyx** [comment]
![loss7](https://user-images.githubusercontent.com/1645737/75968429-a4897580-5ecd-11ea-9235-2f5aebc2cba2.png)
La désactivation de `automatic_mixed_precision` permet bien d'avoir un dev loss plus stable, et un point de sélection du "best dev model" à la même étape du processus d'entraînement.

**Comment by lissyx** [comment]
J'ai fait plein d'essais avec des dropout différents, 0.25, 0.40, 0.45 mais rien qui n'améliore sérieusement les choses.

**Comment by lissyx** [comment]
https://github.com/Common-Voice/commonvoice-fr/releases/tag/v0.6.0-fr-0.4
